cns/urls.py
# urls.py

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from user.views import DashboardView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('service/', include('service.urls')),
    path('info/', include('info_pages.urls')),
    path('', DashboardView.as_view(), name='dashboard'),

    
]

# Add static files serving during development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Urban Service Hub'
admin.site.site_title = 'USH'

service/urls.py
from django.urls import path, include
from service.views import *


app_name = 'service'

urlpatterns = [
    path('service-create', ServiceCreateView.as_view(), name='service_create'),
    path('service-detail/<int:provider_service>', ServiceDetailView.as_view(), name='service_detail'),
    path('service-booking/<int:provider_service>', ServiceBookingView.as_view(), name='service_booking'),
    path('service-payment', service_payment, name='service_payment'),
    path('service-booking-done', ServiceBookingDoneView.as_view(), name='service_boooking_done'),
    path('service-list', ServiceListView.as_view(), name='service_list'),
    path('feedback', FeedbackCreateView.as_view(), name='feedback'),
]

service/forms.py
from django import forms
from .models import *

class SearchForm(forms.Form):
    search_input = forms.CharField(label='What are you looking for?', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Car Repair Services'}), max_length=255)


class ServiceCreateForm(forms.Form):
    title = forms.CharField(label='Service Title', max_length=255, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Service Name'}))
    category = forms.CharField(label='Category', widget=forms.Select(attrs={'class': 'select'}))
    price = forms.DecimalField(label='Price', widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Set 0 for free'}))
    description = forms.CharField(label='Description', widget=forms.Textarea(attrs={'class': 'form-control ck-editor'}))
    monday_from_time = forms.TimeField(label='Monday - From', widget=forms.TimeInput(attrs={'class': 'form-control timepicker', 'placeholder': 'From'}))
    monday_to_time = forms.TimeField(label='Monday - To', widget=forms.TimeInput(attrs={'class': 'form-control timepicker', 'placeholder': 'To'}))
    tuesday_from_time = forms.TimeField(label='Tuesday - From', widget=forms.TimeInput(attrs={'class': 'form-control timepicker', 'placeholder': 'From'}))
    tuesday_to_time = forms.TimeField(label='Tuesday - To', widget=forms.TimeInput(attrs={'class': 'form-control timepicker', 'placeholder': 'To'}))
    wednesday_from_time = forms.TimeField(label='Wednesday - From', widget=forms.TimeInput(attrs={'class': 'form-control timepicker', 'placeholder': 'From'}))
    wednesday_to_time = forms.TimeField(label='Wednesday - To', widget=forms.TimeInput(attrs={'class': 'form-control timepicker', 'placeholder': 'To'}))
    thursday_from_time = forms.TimeField(label='Thursday - From', widget=forms.TimeInput(attrs={'class': 'form-control timepicker', 'placeholder': 'From'}))
    thursday_to_time = forms.TimeField(label='Thursday - To', widget=forms.TimeInput(attrs={'class': 'form-control timepicker', 'placeholder': 'To'}))
    friday_from_time = forms.TimeField(label='Friday - From', widget=forms.TimeInput(attrs={'class': 'form-control timepicker', 'placeholder': 'From'}))
    friday_to_time = forms.TimeField(label='Friday - To', widget=forms.TimeInput(attrs={'class': 'form-control timepicker', 'placeholder': 'To'}))
    saturday_from_time = forms.TimeField(label='Saturday - From', widget=forms.TimeInput(attrs={'class': 'form-control timepicker', 'placeholder': 'From'}))
    saturday_to_time = forms.TimeField(label='Saturday - To', widget=forms.TimeInput(attrs={'class': 'form-control timepicker', 'placeholder': 'To'}))
    sunday_from_time = forms.TimeField(label='Sunday - From', widget=forms.TimeInput(attrs={'class': 'form-control timepicker', 'placeholder': 'From'}))
    sunday_to_time = forms.TimeField(label='Sunday - To', widget=forms.TimeInput(attrs={'class': 'form-control timepicker', 'placeholder': 'To'}))
    add1 = forms.CharField(label='Address 1', max_length=255, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Your Address 1'}))
    add2 = forms.CharField(label='Address 2', max_length=255, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Your Address 2'}))
    country = forms.CharField(label='Country', max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Country'}))
    city = forms.CharField(label='City', max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Your City'}))
    provision = forms.CharField(label='Provision', max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Your State'}))
    pincode = forms.CharField(label='Pincode', max_length=10, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Your Pincode'}))
    image = forms.ImageField(label='Image', required=False, widget=forms.FileInput(attrs={'accept': 'image/*'}))

class ServiceBookingForm(forms.Form):
    add1 = forms.CharField(label='Address 1', max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Your Address 1'}))
    add2 = forms.CharField(label='Address 2', max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Your Address 2'}))
    city = forms.CharField(label='City', max_length=50, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Your City'}))
    provision = forms.CharField(label='Provision', max_length=50, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Your State'}))
    country = forms.CharField(label='Country', max_length=50, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Country'}))
    pincode = forms.CharField(label='Pincode', max_length=10, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Your Pincode'}))
    appointment = forms.CharField(label='Category', widget=forms.Select(attrs={'class': 'select'}))
   
class FeedbackForm(forms.Form):
    feedback = forms.CharField(label='Add Feedback', max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Your Feedback'}))
    

service/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.views import View
from service.models import *
from django.shortcuts import render, redirect
from service.forms import *
from user.models import *
from service.forms import *
from service.scripts import *
from django.urls import reverse_lazy, reverse

class ServiceBookingView(View):
    template_name = 'services/service-booking.html'
    base_template = 'base.html'
    active_step = 'appointment'

    def get_context_data(self):
        context = {
            'base_template': self.base_template,
            'user_name': 'John Smith1',
            'member_since': 'Sep 2021',
            'active_step': self.active_step,
        }
        try:
            user = User.objects.get(pk=self.request.user_id)
            context['user_type'] = user.user_type.user_type
            context['user'] = user
        except User.DoesNotExist:
            return redirect('user:user_signin')
        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context_data()
        provider_service_id = kwargs.get('provider_service')
        provider_service = ProviderService.objects.get(pk=provider_service_id)
        context['provider_service'] = provider_service
        service_availability = ProviderAvailability.objects.filter(service = provider_service)
        context['service_availabilities'] = service_availability
        form = ServiceBookingForm()
        form.fields['appointment'].choices = [(str(avail.pk), f"{avail.start_time} - {avail.end_time}") for avail in service_availability]
        context['form'] = form
        return render(request, self.template_name, context=context)

    def post(self, request, *args, **kwargs):
        context = self.get_context_data()
        provider_service_id = kwargs.get('provider_service')
        appointment_time = request.POST.get('appointment')
        provider_service = ProviderService.objects.get(pk = provider_service_id)
        form = ServiceBookingForm(request.POST)  # Pass POST data and service_availabilities to the form
        if form.is_valid():
            add1 = form.cleaned_data['add1']
            add2 = form.cleaned_data['add2']
            city = form.cleaned_data['city']
            provision = form.cleaned_data['provision']
            country = form.cleaned_data['country']
            pincode = form.cleaned_data['pincode']
            appointment = form.cleaned_data['appointment']
            address = Address.objects.create(add1=add1, add2=add2, city=city, provision=provision, country=country, postal_code=pincode)
            service_booking = ServiceBooking.objects.create(user = context['user'], service=provider_service, address=address, appointment_time=appointment)
            return HttpResponseRedirect(reverse('service:service_boooking_done'))
        else:
            print("Form is not valid")
            print("Errors:", form.errors)
        context['form'] = form  # Include the form in the context
        return render(request, self.template_name, context=context)

class ServiceDetailView(View):
    template_name = 'services/service-detail.html'
    base_template = 'base.html'

    def get(self, request, provider_service):
        context = {'base_template': self.base_template}
        try:
            user = User.objects.get(pk=request.user_id)
            context['user_type'] = user.user_type.user_type
            context['user'] = user
            provider_service = ProviderService.objects.get(pk = provider_service)
            service_availability = ProviderAvailability.objects.filter(service = provider_service)
            context['provider_service'] = provider_service
            context['service_availability'] = service_availability
        except Exception as e:
            pass
        return render(request, self.template_name, context=context)

def service_payment(request):
    context = {"base_template":"base.html", "active_step":"payment", "active_header":"providers"}
    try:
        user = User.objects.get(pk=request.user_id)
        context['user_type'] = user.user_type.user_type
        context['user'] = user
    except Exception as e:
        pass
    return render(request, 'services/service-booking-payment.html', context=context)

class ServiceBookingDoneView(View):
    template_name = 'services/service-booking-done.html'
    base_template = 'base.html'
    active_step = 'done'
    active_header = 'providers'

    def get_context_data(self):
        context = {
            'base_template': self.base_template,
            'active_step': self.active_step,
            'active_header': self.active_header,
        }
        try:
            user = User.objects.get(pk=self.request.user_id)
            context['user_type'] = user.user_type.user_type
            context['user'] = user
        except User.DoesNotExist:
            return redirect('user:user_signin')
        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context_data()
        return render(request, self.template_name, context=context)

class ServiceListView(View):
    template_name = 'services/service-list.html'
    base_template = 'base.html'
    form_class = SearchForm

    def get(self, request, *args, **kwargs):
        context = {"base_template":self.base_template, "active_header":"providers"}
        try:
            user_id = request.user_id
            user = User.objects.get(pk = user_id)
            context['user_type'] = user.user_type.user_type
            if user.user_type.user_type == 'provider':
                provider_services = ProviderService.objects.filter(provider = user)
            else:
                provider_services = ProviderService.objects.all()
            service_ratings_data = {}
            for service in provider_services:
                service_ratings_data[service.id] = 0
                bookings = ServiceBooking.objects.filter(service = service)
                total_ratings = 0
                service_ratings_length = 1
                for booking in bookings:
                    service_ratings = ServiceRating.objects.filter(service=booking)
                    service_ratings_length = service_ratings_length+len(service_ratings)
                    for service_rate in service_ratings:
                        total_ratings = total_ratings+service_rate.rate
                if total_ratings != 0 or total_ratings != 0.0:
                    service_ratings_data[service.id] = round(total_ratings/service_ratings_length,1)
            context['provider_services'] = provider_services
            context['user'] = user
            context['user'] = user
            context['service_ratings'] = service_ratings_data
            context['form'] = self.form_class()
        except Exception as e:
            print("89-----",e)
            return redirect('user:user_signin')
        return render(request, self.template_name, context=context)

    def post(self, request, *args, **kwargs):
        context = {"base_template":self.base_template, "active_header":"providers"}
        form = self.form_class(request.POST)
        context['form'] = self.form_class()
        if form.is_valid():
            search_input = form.cleaned_data.get('search_input')
            user_id = request.user_id
            user = User.objects.get(pk = user_id)
            context['user_type'] = user.user_type.user_type
            if search_input != '':
                if user.user_type.user_type == 'provider':
                    provider_services = ProviderService.objects.filter(provider = user, title__icontains = search_input)
                else:
                    provider_services = ProviderService.objects.filter(title__icontains = search_input)
            else:
                provider_services = ProviderService.objects.filter(provider = user)
            service_ratings_data = {}
            for service in provider_services:
                service_ratings_data[service.id] = 0
                bookings = ServiceBooking.objects.filter(service = service)
                total_ratings = 0
                service_ratings_length = 1
                for booking in bookings:
                    service_ratings = ServiceRating.objects.filter(service=booking)
                    service_ratings_length = service_ratings_length+len(service_ratings)
                    for service_rate in service_ratings:
                        total_ratings = total_ratings+service_rate.rate
                if total_ratings != 0 or total_ratings != 0.0:
                    service_ratings_data[service.id] = round(total_ratings/service_ratings_length,1)
            context['provider_services'] = provider_services
            context['user'] = user
            context['service_ratings'] = service_ratings_data
            context['search_input'] = search_input
            return render(request, self.template_name, context=context)
        else:
            return render(request, self.template_name, context=context)

class ServiceCreateView(View):
    template_name = 'services/service-create.html'
    base_template = 'base.html'
    active_header = 'providers'
    form_class = ServiceCreateForm

    def get_initial_data(self, provider_service=None, service_avalibilities=None):
        initial_data = {}
        if provider_service:
            initial_data = {
                'title': provider_service.title,
                'category': provider_service.category.name,
                'price': provider_service.price,
                'description': provider_service.desc,
                'add1': provider_service.address.add1,
                'add2': provider_service.address.add2,
                'country': provider_service.address.country,
                'city': provider_service.address.city,
                'provision': provider_service.address.provision,
                'pincode': provider_service.address.postal_code,

service/templates/services/service-detail.html
{% load static %}

{% if base_template == 'base.html' %}
    {% include 'head.html' %}
    {% include 'header.html' %}
    <body class="base-body">
{% elif base_template == 'provider-base.html' %}
    {% include 'head.html' %}
    {% include 'header.html' %}
    <body class="provider-body">
{% endif %}
    <div class="breadcrumb-bar">
        <div class="container">
          <div class="row">
            <div class="col-md-12 col-12">
              <h2 class="breadcrumb-title">Service Details</h2>
              <nav aria-label="breadcrumb" class="page-breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="http://127.0.0.1:8000">Home</a></li>
                  <li class="breadcrumb-item active" aria-current="page">
                    Service Details
                  </li>
                </ol>
              </nav>
            </div>
          </div>
        </div>
    </div>
    <div class="content">
        <div class="container">
          <div class="row">
            <div class="col-md-8">
              <div class="serv-profile">
                <h2>{{provider_service.title}}</h2>
                <ul>
                  <li>
                    <span class="badge">{{provider_service.category.name}}</span>
                  </li>
                </ul>
              </div>
            </div>

            <div class="col-md-12">
              <div class="service-gal">
                <div class="row gx-2">
                  <div class="col-md-12">
                    <div class="service-images big-gallery">
                        {% if provider_service.pricture %}
                          <img class="img-fluid" src="{{provider_service.picture.url}}" alt="image">
                        {% else %}
                          <img src="{% static 'assets/img/services/service-04.jpg' %}" alt="image">
                        {% endif %}
                    </div>
                  </div>
                  
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-8">
              <div class="service-wrap">
                <h5>Service Details</h5>
                <p>
                  {{provider_service.desc}}
                </p>
              </div>
              <div class="service-wrap provide-service">
                <h5>Service Provider</h5>
                <div class="row">
                  <div class="col-md-4">
                    <div class="provide-box">
                      <span><i class="feather-user"></i></span>
                      <div class="provide-info">
                        <h6>Member Since</h6>
                        <p>{{user.created_at}}</p>
                      </div>
                    </div>
                  </div>
                  <div class="col-md-4">
                    <div class="provide-box">
                      <span><i class="feather-map-pin"></i></span>
                      <div class="provide-info">
                        <h6>Address</h6>
                        <p>{{user.address.city}}, {{user.address.provision}}, {{user.address.country}}</p>
                      </div>
                    </div>
                  </div>
                  <div class="col-md-4">
                    <div class="provide-box">
                      <span><i class="feather-mail"></i></span>
                      <div class="provide-info">
                        <h6>Email</h6>
                        <p>
                            {{user.email}}
                        </p>
                      </div>
                    </div>
                  </div>
                  <div class="col-md-4">
                    <div class="provide-box">
                      <span><i class="feather-phone"></i></span>
                      <div class="provide-info">
                        <h6>Phone</h6>
                        <p>{{user.phone_number}}</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="col-lg-4 theiaStickySidebar">
              <div class="card card-provide mb-0">
                <div class="card-body">
                  <div class="provide-widget">
                    <div class="service-amount">
                      <h5>${{provider_service.price}}</h5>
                      
                    </div>
                    <div class="serv-proimg">
                        {% if user.avatr %}
                                                                <img src="{{user.avatar.url}}"
                                                                    alt="user">
                                                                {% else %}
                                                                <img src="{% static 'assets/img/profiles/avatar-02.jpg' %}" alt="user">
                                                                {% endif %}
                      <span><i class="fa-solid fa-circle-check"></i></span>
                    </div>
                  </div>
                  <div class="card card-available">
                    <div class="card-body">
                      <div class="available-widget">
                        <div class="available-info">
                          <h5>Service Availability</h5>
                          <ul>
                            {% for avail in service_availability %}
                            <li>{{avail.day}} <span>{{avail.start_time}} - {{avail.end_time}}</span></li>
                            
                            {% endfor %}
                          </ul>
                        </div>
                      </div>
                    </div>
                  </div>
                  {% if user.user_type.user_type == "provider" %}
                    <a href="http://127.0.0.1:8000/service/service-create?provider_service_id={{provider_service.id}}" class="btn btn-primary">Edit Service<i class="feather-arrow-right-circle ms-1"></i></a>
                  {% else %}

                    <a href="{% url 'service:service_booking'  provider_service=provider_service.id %}" class="btn btn-primary">Book Service<i class="feather-arrow-right-circle ms-1"></i></a>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
{% include 'footer.html' %}

service/templates/services/service-list.html
{% load static %}

{% if base_template == 'base.html' %}
{% include 'head.html' %}
{% include 'header.html' %}
{% load custom_filters %}
<body class="base-body">
    {% elif base_template == 'provider-base.html' %}
    {% include 'head.html' %}
    {% include 'header.html' %}

    <body class="provider-body">
        {% endif %}
        <div class="main-wrapper">
            <div class="bg-img">
                <img src="{% static 'assets/img/bg/work-bg-03.png' %}" alt="img" class="bgimg1">
                <img src="{% static 'assets/img/bg/work-bg-03.png' %}" alt="img" class="bgimg2">
                <img src="{% static 'assets/img/bg/feature-bg-03.png' %}" alt="img" class="bgimg3">
            </div>
            <div class="breadcrumb-bar">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12 col-12">
                            <h2 class="breadcrumb-title">Services</h2>
                            <nav aria-label="breadcrumb" class="page-breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">Service List</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12col-sm-12">
                            <div class="row">
                                <div class="search-box">
                                      <form action="{% url 'service:service_list' %}" method="post">
                                        {% csrf_token %}
                                        <div class="search-input line">
                                        </div>
                                        <div class="search-input">
                                          <div class="search-group-icon search-icon">
                                            <i class="feather-search"></i>
                                          </div>
                                          <div class="form-group mb-0">
                                            <label>What are you looking for?</label>
                                            {% if search_input %}
                                                <input type="text" class="form-control" name="search_input" value="{{ search_input }}">
                                            {% else %}
                                                {{form.search_input}}
                                            {% endif %}
                                          </div>
                                        </div>
                                        <div class="search-btn">
                                          <button class="btn btn-primary" type="submit"><i class="feather-search me-2"></i>Search</button>
                                        </div>
                                      </form>
                                    </div>
                                <div class="col-md-12">
                                <br>
                                <br>
                                    {% for provider_service in provider_services %}
                                        {% if provider_service.id %}
                                            {% with provider_service_id=provider_service.id %}
                                                <div class="service-list">
                                                    <div class="service-cont">
                                                        <div class="service-cont-img">
                                                            <a href="{% url 'service:service_detail' provider_service.id %}">
                                                                {% if provider_service.picture %}
                                                                    <img class="img-fluid serv-img" alt="Service Image" src="{{ provider_service.picture.url }}">
                                                                {% else %}
                                                                    <img class="img-fluid serv-img" alt="Default Service Image" src="{% static 'assets/img/services/service-ban-01.jpg' %}">
                                                                {% endif %}
                                                            </a>
                                                        </div>
                                                        <div class="service-cont-info">
                                                            <span class="item-cat">{{provider_service.category.name}}</span>
                                                            <h3 class="title">
                                                                <a
                                                                    href="http://127.0.0.1:8000/service/service-detail">{{provider_service.title}}</a>
                                                            </h3>
                                                            <p><i class="feather-map-pin"></i>{{provider_service.address.city}},
                                                                {{provider_service.address.provision}},
                                                                {{provider_service.address.country}}</p>
                                                            <div class="service-pro-img">
                                                                {% if user.avatr %}
                                                                <img src="{{user.avatar.url}}"
                                                                    alt="user">
                                                                {% else %}
                                                                <img src="{% static 'assets/img/profiles/avatar-02.jpg' %}" alt="user">
                                                                {% endif %}
                                                                 <span><i class="fas fa-star filled"></i>{{service_ratings|get_by_key:provider_service.id}}</span>
                                                                
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="service-action">
                                                        <h6>${{provider_service.price}}</h6>
                                                        {% if user %}
                                                            {% if user.user_type.user_type == "customer" %}
                                                                <a href="{% url 'service:service_booking'  provider_service=provider_service_id %}"
                                                                    class="btn btn-secondary">Book Now</a>
                                                            {% endif %}
                                                        {% endif %}
                                                    </div>
                                                </div>
                                            {% endwith %}
                                        {% endif %}
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {% include 'footer.html' %}