cns/urls.py
# urls.py

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from user.views import DashboardView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('service/', include('service.urls')),
    path('info/', include('info_pages.urls')),
    path('', DashboardView.as_view(), name='dashboard'),

    
]

# Add static files serving during development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Urban Service Hub'
admin.site.site_title = 'USH'

user/urls.py
from django.urls import path, include
from user.views import *

app_name = 'user'

urlpatterns = [
    # path('', dashboard, name='dashboard'),
    path('choose_register', ChooseRegisterView.as_view(), name='choose_register'),  # Add this line
    path('provider_signup', ProviderSignupView.as_view(), name='provide_signup'),
    path('verify-email', VerifyEmailView.as_view(), name='verify_email'),
    path('verify-mail', VerifyEmailSuccessView.as_view(), name='verify_email_successful'),
    path('user_signup', UserSignupView.as_view(), name='user_signup'),
    path('forgot-password', ForgotPasswordView.as_view(), name='forgot_password'),
    path('reset-password', ResetPasswordView.as_view(), name='reset_password'),
    path('user_signin', UserSigninView.as_view(), name='user_signin'),

    # Provider Routes
    path('provider-services', ProviderServicesView.as_view(), name='provider_services'),
    path('provider-booking', ProviderBookingView.as_view(), name='provider_booking'),
    path('provider-list', ProviderListView.as_view(), name='provider_list'),
    path('provider-details/<int:provider_id>', ProviderDetailsView.as_view(), name='provider_details'),
    path('provider-profile', ProviderProfileView.as_view(), name='provider_rofile'),
    path('service-complete/<int:service_id>', ServiceCompleteView.as_view(), name='service_complete'),

    # customer Routes
    path('customer-booking', CustomerBookingView.as_view(), name='customer_booking'),
    path('customer-profile', CustomerProfileView.as_view(), name='customer_rofile'),
]

user/models.py
import pytz
import random
from datetime import datetime, timedelta
from django.conf import settings
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)
from django.core.validators import ValidationError
from django.db import models
from rest_framework_simplejwt.tokens import RefreshToken
from math import sin, cos, sqrt, atan2, radians
import string
import uuid
from django.utils import timezone
from django.core.validators import MinValueValidator

def avatar_path(instance, filename):
    return 'avatar/{}/{}'.format(
        instance.id,
        filename
    )

class UserManager(BaseUserManager):
    def create_user(self, username, password):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not username:
            raise ValueError('Users must have an email address')

        user = self.model(
            username=self.normalize_email(username),
        )
        user.phone_number = "1234567890"
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            username=username,
            password=password,
        )
        user.phone_number = "1234567890"
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class UserType(models.Model):
    USER_TYPE_CHOICES = (
        ('customer', 'Customer'),
        ('provider', 'Provider')
    )
    user_type = models.CharField(max_length=50, choices=USER_TYPE_CHOICES, default='user', null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.get_user_type_display()


class Address(models.Model):
    ADDRESS_TYPE_CHOICES = (
        ('user', 'User'),
        ('serviceprovider', 'ServiceProvider'),
        ('servicebooking', 'ServiceBooking')
    )
    add1 = models.CharField(max_length=255, null=False, blank=False)
    add2 = models.CharField(max_length=255, null=True, blank=True)
    city = models.CharField(max_length=50, null=False, blank=False)
    address_type = models.CharField(choices=ADDRESS_TYPE_CHOICES, default="user", max_length=50, null=False, blank=False)
    provision = models.CharField(max_length=50, null=False, blank=False)
    country = models.CharField(max_length=50, null=False, blank=False)
    postal_code = models.CharField(max_length=20, null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.id}"

class User(AbstractBaseUser):
    GENDER_CHOICES = (('male', 'Male'), ('female', 'Female'), ('other', 'Other'))
    CURRENCY_CHOICES = (('cad', 'CAD'), ('usd', 'USD'))
    def save(self, *args, **kwargs):
        if self.pk == None:
            if not (self.email == None or self.email == ""):
                if User.objects.filter(email=self.email).exists():
                    return ValidationError("User Already Exist in  this mail id")

            if (self.username == None or self.username == ""):
                first_name = self.first_name
                if first_name:
                    username = "_".join(first_name.split(" "))+str(random.randrange(99999, 999999, 12))
                    if User.objects.filter(username=username).exists():
                        uid = User.objects.last().id + 1
                        self.username = f"{username}_{uid}"
                    else:
                        self.username = f"{username}"

                email = self.email
                if email and not self.username:
                    mail_id = email.split("@")[0].lower()
                    if User.objects.filter(username=mail_id).exists():
                        uid = User.objects.last().id + 1
                        self.username = f"{mail_id}_{uid}"
                    else:
                        self.username = f"{mail_id}"

            self.username = self.username.lower()
            if self.email:
                self.email = self.email.lower()

        super(User, self).save(*args, **kwargs)
    user_type = models.ForeignKey(UserType, on_delete=models.CASCADE, default = 1, null=False, blank=False)
    first_name = models.CharField(max_length=50, null=False, blank=False)
    last_name = models.CharField(max_length=50, null=False, blank=False)
    username = models.CharField(max_length=100, null=False, blank=False, unique=True)
    email = models.EmailField(blank=True, null=True, unique=True, db_index=True)
    email_verified = models.BooleanField(default=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False, unique=True)
    avatar = models.ImageField(upload_to=avatar_path, blank=True, null=True)
    availability = models.FloatField(default=0.0)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    address = models.ForeignKey(Address, on_delete=models.CASCADE, null=True, blank=True)
    bio = models.TextField(blank = True)
    experience = models.FloatField(default=0, validators=[MinValueValidator(0)])
    gender = models.CharField(choices=GENDER_CHOICES, default='male', max_length=50, null=False, blank=False)
    currency_code = models.CharField(choices=CURRENCY_CHOICES, default='cad', max_length=50, null=False, blank=False)
    groups = models.ManyToManyField('auth.Group', blank=True, related_name="cutom_user_group")
    objects = UserManager()

    USERNAME_FIELD = "username"

    def __str__(self):
        return f"{self.first_name} {self.last_name} - {self.email}"

    def has_perm(self, perm, obj=None):
        user_perms = []
        if self.is_staff:
            groups = self.groups.all()
            for group in groups:
                perms = [(f"{x.content_type.app_label}.{x.codename}") for x in group.permissions.all()]
                user_perms += perms

            if perm in user_perms:
                return True
        return (self.is_admin or self.is_superuser)

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        return True

    def get_tokens_for_user(self):
        refresh = RefreshToken.for_user(self)
        data = {
            'refresh': str(refresh),
            'access': str(refresh.access_token),
        }   
        return data

    def generate_random_string(length):
        characters = string.ascii_letters + string.digits  # include both letters and digits
        random_string = ''.join(random.choice(characters) for _ in range(length))
        return random_string


class EmailVerification(models.Model):
    email_to = models.ForeignKey(User, on_delete=models.CASCADE, null = False, blank = False)
    verification_token = models.CharField(max_length=255, blank=False, null=False, )
    validity = models.DateTimeField(blank=True, null=True, )

    def validate_email(self, email_to, verification_token):
        # Checking if the email and verification token match the instance
        valid = (self.email_to == email_to and 
                self.verification_token == verification_token and 
                self.validity >= timezone.now())

        # Deleting the instance if validation is successful
        if valid:
            self.delete()

        return valid

from service.models import ServiceBooking


class ProviderGetInTouch(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender_contacts', null=False, blank=False)
    provider = models.ForeignKey(User, on_delete=models.CASCADE, null=False, related_name='recipient_contacts', blank=False)
    full_name = models.CharField(max_length=80, blank=False, null=False, )
    email = models.EmailField(blank=True, null=True, db_index=True)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    message = models.TextField(blank = True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.user.username)

class UserSystemVisit(models.Model):
    created_at = models.DateTimeField(timezone.now)
    daily_count = models.IntegerField(default=0)
    total_count = models.IntegerField(default=0)

    def __str__(self):
        return str(self.created_at)

        

user/templates/login/forgot-password.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}

<div class="content">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-lg-6 mx-auto">
        <div class="login-wrap">
          <div class="login-header">
            <h3>Password Recovery</h3>
            <p>Enter your email and we will send you a link to reset your password.</p>
          </div>

        <form method="post" action="{% url 'user:forgot_password' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-primary w-100 login-btn" type="submit">Submit</button>
        </form>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="mouse-cursor cursor-outer"></div>
<div class="mouse-cursor cursor-inner"></div>



{% endblock %}

user/templates/login/login.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}

<div class="content">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-lg-6 mx-auto">
                <div class="login-wrap">
                    {% if verification_token %}
                        <p>Email Verified Successfully.</p>
                    {% endif %}
                          <div class="login-header">
                        <h3>Login</h3>
                        <p>Please enter your details</p>
                    </div>

                  <form action="{% url 'user:user_signin' %}" method="post">
                        {% csrf_token %}
                        {% if form.errors %}
                            <div class="alert alert-danger" role="alert">
                                Please correct the errors below.
                            </div>
                        {% endif %}
                        <div class="log-form">
                             <div class="form-group">
                                <label for="id_email">Email</label>
                                {{ form.email }}
                                {% if form.errors.email %}
                                    <small class="text-danger">{{ form.errors.email }}</small>
                                {% endif %}
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col">
                                        <label for="id_password" class="col-form-label">Password</label>
                                    </div>
                                    <div class="col-auto">
                                        <a class="forgot-link" href="http://127.0.0.1:8000/user/forgot-password">
                                            Forgot password?
                                        </a>
                                    </div>
                                </div>
                               <div class="form-group">

                                    <div class="password-wrapper">
                                        <input type="password" class="form-control" id="password-field" placeholder="*************" name="password">
                                        <span class="eye-icon" onclick="togglePasswordVisibility(this)">&#x1F441;</span>
                                    </div>
                                    {% if form.errors.password %}
                                        <small class="text-danger">{{ form.errors.password }}</small>
                                    {% endif %}
                                </div>
                            </div>
                            
                        </div>
                        <button class="btn btn-primary w-100 login-btn" type="submit">Login</button>
                        <div class="login-or">
                            <span class="or-line"></span>
                            <span class="span-or">OR</span>
                        </div>
                        <p class="no-acc">Don't have an account ? <a href="http://127.0.0.1:8000/user/user_signup">Register</a></p>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="mouse-cursor cursor-outer"></div>
<div class="mouse-cursor cursor-inner"></div>
{% endblock %}

user/templates/login/reset-password.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}

<div class="content">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-lg-6 mx-auto">
        <div class="login-wrap">
          <div class="login-header">
            <h3>Reset Password</h3>
              {% if alert %}
                <p>{{alert}}</p>
              {% endif %}
          </div>
          <form method="post" action="{% url 'user:reset_password' %}?token={{ token }}">
            {% csrf_token %}
            <div class="log-form">
              <div class="form-group">
                <input type="hidden" name="token" value="{{ request.GET.token }}">
                <label class="col-form-label">New Password</label>
                <div class="password-wrapper">
                  <input type="password" class="form-control" id="password-1" placeholder='*************' name="password1">
                  <span class="eye-icon" onclick="togglePassword1Visibility(this)">&#x1F441;</span>
                </div>
                {% if form.errors.password1 %}
                    <small class="text-danger">{{ form.errors.password1 }}</small>
                {% endif %}
              </div>
              <div class="form-group">
                <label class="col-form-label">Confirm Password</label>
                <div class="password-wrapper">
                  <input type="password" class="form-control" id="password-2" placeholder='*************' name="password2">
                  <span class="eye-icon" onclick="togglePassword2Visibility(this)">&#x1F441;</span>
                </div>
                {% if form.errors.password2 %}
                    <small class="text-danger">{{ form.errors.password2 }}</small>
                {% endif %}
              </div>
            </div>
            <button class="btn btn-primary w-100 login-btn" type="submit">Save Change</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="mouse-cursor cursor-outer"></div>
<div class="mouse-cursor cursor-inner"></div>

{% endblock %}