cns/urls.py
# urls.py

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from user.views import DashboardView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('service/', include('service.urls')),
    path('info/', include('info_pages.urls')),
    path('', DashboardView.as_view(), name='dashboard'),

    
]

# Add static files serving during development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Urban Service Hub'
admin.site.site_title = 'USH'

service/urls.py
from django.urls import path, include
from service.views import *


app_name = 'service'

urlpatterns = [
    path('service-create', ServiceCreateView.as_view(), name='service_create'),
    path('service-detail/<int:provider_service>', ServiceDetailView.as_view(), name='service_detail'),
    path('service-booking/<int:provider_service>', ServiceBookingView.as_view(), name='service_booking'),
    path('service-payment', service_payment, name='service_payment'),
    path('service-booking-done', ServiceBookingDoneView.as_view(), name='service_boooking_done'),
    path('service-list', ServiceListView.as_view(), name='service_list'),
    path('feedback', FeedbackCreateView.as_view(), name='feedback'),
]

user/urls.py
from django.urls import path, include
from user.views import *

app_name = 'user'

urlpatterns = [
    # path('', dashboard, name='dashboard'),
    path('choose_register', ChooseRegisterView.as_view(), name='choose_register'),  # Add this line
    path('provider_signup', ProviderSignupView.as_view(), name='provide_signup'),
    path('verify-email', VerifyEmailView.as_view(), name='verify_email'),
    path('verify-mail', VerifyEmailSuccessView.as_view(), name='verify_email_successful'),
    path('user_signup', UserSignupView.as_view(), name='user_signup'),
    path('forgot-password', ForgotPasswordView.as_view(), name='forgot_password'),
    path('reset-password', ResetPasswordView.as_view(), name='reset_password'),
    path('user_signin', UserSigninView.as_view(), name='user_signin'),

    # Provider Routes
    path('provider-services', ProviderServicesView.as_view(), name='provider_services'),
    path('provider-booking', ProviderBookingView.as_view(), name='provider_booking'),
    path('provider-list', ProviderListView.as_view(), name='provider_list'),
    path('provider-details/<int:provider_id>', ProviderDetailsView.as_view(), name='provider_details'),
    path('provider-profile', ProviderProfileView.as_view(), name='provider_rofile'),
    path('service-complete/<int:service_id>', ServiceCompleteView.as_view(), name='service_complete'),

    # customer Routes
    path('customer-booking', CustomerBookingView.as_view(), name='customer_booking'),
    path('customer-profile', CustomerProfileView.as_view(), name='customer_rofile'),
]

user/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import PasswordResetView
from django.core.mail import send_mail
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.hashers import make_password, check_password
from django.urls import reverse_lazy, reverse
from pyexpat.errors import messages
from cns import settings
from service.models import *
from user.forms import *
from user.models import *
from django.views import View
from django.http import HttpResponseRedirect
from django.contrib import messages
from user.templatetags.custom_message import custom_message
from user.scripts import *
from notifications.scripts import *
from user.utils import *
from django.views.generic import TemplateView
from service.models import *


class DashboardView(View):
    template_name = 'index.html'
    base_template = 'base.html'

    def get(self, request, *args, **kwargs):
        action = request.GET.get('action', None)
        if action=='logout':
            request.session.pop('access_token', None)
            return HttpResponseRedirect(reverse('dashboard'))
        context = {}
        try:
            services = [
            {
                "link": "service-details.html",
                "image": "../../static/assets/img/services/service-01.jpg",
                "category": "Plumbing",
                "provider_image": "../../static/assets/img/profiles/avatar-05.jpg",
                "title": "Pipe Installation & Repair",
                "location": "New York, NY, USA",
                "rating": "4.8",
                "price": "$30.00",
                # "old_price": "$45.00"
            },
            {
                "link": "service-details.html",
                "image": "../../static/assets/img/services/service-02.jpg",
                "category": "Electrical",
                "provider_image": "../../static/assets/img/profiles/avatar-06.jpg",
                "title": "Electrical Installation",
                "location": "Los Angeles, CA, USA",
                "rating": "4.9",
                "price": "$50.00",
                "old_price": "$60.00"
            },
            {
                "link": "service-details.html",
                "image": "../../static/assets/img/services/service-03.jpg",
                "category": "Painting",
                "provider_image": "../../static/assets/img/profiles/avatar-07.jpg",
                "title": "House Painting",
                "location": "Chicago, IL, USA",
                "rating": "4.7",
                "price": "$40.00",
                    # "old_price": "$55.00"
                },
            ]
            context['services'] = services
            context['base_template'] = 'base.html'
            context['active_header'] = 'home'
            try:
                user = User.objects.get(pk=request.user_id)
                context['user_type'] = user.user_type.user_type
                context['user'] = user

                if user.user_type.user_type=="provider":
                    return HttpResponseRedirect(reverse('user:provider_booking'))
                return HttpResponseRedirect(reverse('user:customer_booking'))
            except Exception as e:
                pass
            providers = User.objects.filter(user_type__user_type='provider')
            services = ProviderService.objects.all().order_by("-id")
            context['providers'] = providers
            context['services'] = services
            return render(request, self.template_name, context=context)
        except Exception as e:
            context = {'base_template': self.base_template}
            return render(request, self.template_name, context=context)


class ChooseRegisterView(View):
    template_name = 'register/choose_signup.html'
    base_template = 'base.html'

    def get(self, request, *args, **kwargs):
        try:
            user_id = request.user_id
            user = User.objects.get(pk = user_id)
            if user.user_type.user_type=="provider":
                return HttpResponseRedirect(reverse('user:provider_booking'))
            return HttpResponseRedirect(reverse('user:customer_booking'))
        except Exception as e:
            context = {'base_template': self.base_template}
            return render(request, self.template_name, context=context)


class ProviderSignupView(View):
    template_name = 'register/provider-signup.html'
    base_template = 'base.html'
    form_class = ProviderSignupForm

    def get(self, request, *args, **kwargs):
        try:
            user_id = request.user_id
            user = User.objects.get(pk = user_id)
            if user.user_type.user_type=="provider":
                return HttpResponseRedirect(reverse('user:provider_booking'))
            return HttpResponseRedirect(reverse('user:customer_booking'))
        except Exception as e:
            form = self.form_class()
            context = {'base_template': self.base_template, 'form': form}
            return render(request, self.template_name, context=context)


    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        context = {'base_template': self.base_template, 'form': form}
        if form.is_valid():
            # Process the data in form.cleaned_data
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            phone = form.cleaned_data['phone']
            password = form.cleaned_data['password']
            user = User.objects.filter(email = email)
            if user:
                if not user.last().email_verified:
                    messages.error(request, "Please verify your email.")
                    return HttpResponseRedirect(reverse('user:verify_email'))
            user_type = UserType.objects.get(user_type = 'provider')
            user = User.objects.create(email = email, user_type = user_type, first_name = first_name, last_name = last_name, phone_number=phone)
            user.set_password(password)
            user.email_verified = False
            user.save()
            verification_token = generate_verification_token()
            verification_link = generate_user_account_verification_link(verification_token, "user/verify-mail?token=")
            EmailVerification.objects.get_or_create(email_to = user, verification_token = verification_token)
            send_account_verification_mail("Verify your email to create your USH Account",first_name, verification_link, email)
            context['success_message'] = "Signup successful!"
            context['user'] = user
            return HttpResponseRedirect(reverse('user:verify_email'))  # Redirect to the index page

        
        return render(request, self.template_name, context=context)

class VerifyEmailView(View):
    template_name = 'register/verify_email.html'
    base_template = 'base.html'

    def get(self, request, *args, **kwargs):
        try:
            user_id = request.user_id
            user = User.objects.get(pk = user_id)
            if user.user_type.user_type=="provider":
                return HttpResponseRedirect(reverse('user:provider_booking'))
            return HttpResponseRedirect(reverse('user:customer_booking'))
        except Exception as e:
            context = {"base_template": self.base_template}
            return render(request, self.template_name, context=context)


class VerifyEmailSuccessView(View):
    template_name = 'login/login.html'
    base_template = 'base.html'

    def get(self, request, *args, **kwargs):
        try:
            user_id = request.user_id
            user = User.objects.get(pk = user_id)
            if user.user_type.user_type=="provider":
                return HttpResponseRedirect(reverse('user:provider_booking'))
            return HttpResponseRedirect(reverse('user:customer_booking'))
        except Exception as e:
            context = {"base_template": self.base_template}
            verification_token = request.GET.get('token', None)
            if not verification_token:
                context['verification_token'] = False
                return render(request, self.template_name, context=context)

            email_verification = get_object_or_404(EmailVerification, verification_token=verification_token)
            user = email_verification.email_to
            if user and email_verification.validate_email(user, verification_token):
                if not user.email_verified:
                    user.email_verified = True
                    user.save()
                    context['verification_token'] = True
            else:
                context['verification_token'] = False

            return render(request, self.template_name, context=context)

class UserSignupView(View):
    template_name = 'register/user_signup.html'
    base_template = "base.html"
    form_class = UserSignupForm

    def get(self, request, *args, **kwargs):
        try:
            user_id = request.user_id
            user = User.objects.get(pk = user_id)
            if user.user_type.user_type=="provider":
                return HttpResponseRedirect(reverse('user:provider_booking'))
            return HttpResponseRedirect(reverse('user:customer_booking'))
        except Exception as e:
            form = self.form_class()
            context = {"base_template": self.base_template, "form": form}
            return render(request, self.template_name, context=context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        context = {'base_template': self.base_template, 'form': form}
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            phone = form.cleaned_data['phone']

user/templates/provider/provider-booking.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}
{% include 'provider/provider-sidebar.html' %}
{% load custom_filters %}
<div class="page-wrapper">
    <div class="content container-fluid">

        <div class="page-header">
            <div class="row">
                <div class="col-md-4">
                    <div class="provider-subtitle">
                        <h6>Booking List</h6>
                    </div>
                </div>
                
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">

                {% for provider_booking in provider_bookings %}
                <div class="booking-list">
                    <div class="booking-widget">
                        <div class="booking-img">
                            <a href="{% url 'service:service_detail' provider_booking.service.id %}">
                                <img src="{{provider_booking.service.picture.url}}" alt="User Image">
                            </a>

                        </div>
                        <div class="booking-det-info">
                            <h3>
                                <a
                                    href="{% url 'service:service_detail' provider_booking.service.id %}">{{provider_booking.service.title|capfirst}}</a>
                                {% if provider_booking.status == 'completed' %}
                                    <span class="badge badge-success">{{provider_booking.status|capfirst}}</span>
                                {% elif provider_booking.status == 'pending' %}
                                    <span class="badge badge-warning">{{provider_booking.status|capfirst}}</span>
                                {% elif provider_booking.status == 'cancelledbyprovider' %}
                                    <span class="badge badge-danger">Cancelled by Provider</span>
                                {% else %}
                                    <span class="badge badge-danger">Cancelled by User</span>
                                {% endif %}
                            </h3>
                            <ul class="booking-details">
                                <li>
                                    <span class="book-item">Booking Date</span> : {{provider_booking.appointment_time}}
                                </li>
                                <li>
                                    <span class="book-item">Amount</span> : ${{provider_booking.price}} <span
                                        class="badge-grey">COD</span>
                                </li>
                                <li>
                                    <span class="book-item">Location</span> : {{provider_booking.address.add1}}
                                    {{provider_booking.address.add2}}, {{provider_booking.address.city}},
                                    {{provider_booking.address.provision}}, {{provider_booking.address.country}},
                                    {{provider_booking.address.postal_code}}
                                </li>
                                <li>
                                    <span class="book-item">Customer</span> :
                                    <div class="user-book">
                                        <div class="avatar avatar-xs">
                                            {% if provider_booking.user.avatar and provider_booking.user.avatar.url %}
                                            <img class="avatar-img rounded-circle"
                                                src="{{ provider_booking.user.avatar.url }}" alt="Avatar">
                                            {% else %}
                                            <img class="avatar-img rounded-circle"
                                                src="{% static 'assets/img/profiles/avatar-02.jpg' %}"
                                                alt="Default Avatar">
                                            {% endif %}
                                        </div>
                                        {{provider_booking.user.first_name}} {{provider_booking.user.last_name}}
                                    </div>
                                    <p>{{provider_booking.user.phone_number}}</p>
                                    </p>
                                    <p>{{provider_booking.user.email}}</p>
                                </li>
                            </ul>
                        </div>
                    </div>
                    {% if provider_booking.status == 'completed' %}
                    <div class="rating text-center">
                        {% for rating in service_ratings|get_by_key:provider_booking.id %}
                            {% for star in rating %}
                                <i class="fas fa-star filled" style="color: gold;"></i>
                            {% endfor %}
                        {% endfor %}
                    </div>
                    {% else %}
                    {% if user.user_type.user_type == 'provider' %}
                    {% if provider_booking %}
                        {% with provider_service_id=provider_booking.id %}
                            <a href="{% url 'user:service_complete' provider_booking.id %}" class="btn btn-primary add-set"><i class="feather-plus me-2"></i>Completed</a>
                        {% endwith %}
                    {% endif %}
                    {% endif %}
                    {% endif %}
                </div>
                {% endfor %}

            </div>
        </div>
    </div>
</div>
{% endblock %}

user/templates/provider/provider-details.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}
<div class="breadcrumb-bar">
    <br>
    <br>
    <br>
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h2 class="breadcrumb-title mb-0">{{user.first_name}} {{user.last_name}}</h2>
                    </div>
                </div>
            </div>
        </div>


        <div class="content">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-md-5">
                        <div class="provider-img">
                            {% if user.avatar %}
                                <img src="{{user.avatar.url}}" class="img-fluid" alt="img">
                            {% else %}
                                <img src="{% static 'assets/img/provider/provider.png' %}" class="img-fluid" alt="img">
                            {% endif %}
                           
                        </div>
                    </div>
                    <div class="col-md-7">
                        <div class="provider-info">
                            <h2>{{user.first_name}} {{user.last_name}}</h2>
                            <h5>{{user.user_type.user_type}}</h5>
                            <p>{{user.bio}}</p>
                            <div class="row">
                                <div class="col-lg-6 col-md-12">
                                    <div class="provide-box">
                                        <span><i class="feather-mail"></i></span>
                                        <div class="provide-info">
                                            <h6>Email</h6>
                                            <p><a
                                                    class="__cf_email__"
                                                    >{{user.email}}</a>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-12">
                                    <div class="provide-box">
                                        <span><i class="feather-phone"></i></span>
                                        <div class="provide-info">
                                            <h6>Phone</h6>
                                            <p>{{user.phone_number}}</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-12">
                                    <div class="provide-box">
                                        <span><i class="feather-map-pin"></i></span>
                                        <div class="provide-info">
                                            <h6>Address</h6>
                                            <p>{{user.address.add1}} {{user.address.add2}}, {{user.address.city}}, {{user.address.provision}}, {{user.address.city}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="provider-details">
                            <h5>Service Details</h5>
                            {% if is_provider_service == 'no' %}
                                <p>No Data</p>
                            {% else %}
                                <p>{{provider_service.last.desc}}</p>
                            {% endif %}
                        </div>
                        <div class="provider-details provide-area">
                            <h5>Areas of Expertise</h5>
                            
                            {% if is_provider_service == 'no' %}
                                <p>Not Listed Any Service By Provider.</p>
                            {% else %}
                                <div class="row">
                                {% for service in provider_service %}
                                <div class="col-lg-2 col-md-4 col-sm-6 d-flex">
                                    <div class="construct-box flex-fill">
                                        <img src="{% static 'assets/img/icons/feature-icon-01.svg' %}" alt="img">
                                        <h6>{{service.category.name}}</h6>
                                    </div>
                                </div>
                                {% endfor %}
                                
                            </div>
                            {% endif %}
                        </div>
                        

                        <div class="contact-queries">
                            <h2>Get In Touch With {{user.first_name}} {{user.last_name}}</h2>
                            <form action="{% url 'user:provider_details' provider_id=user.id %}" method="post">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label class="col-form-label">{{ form.name.label }}</label>
                                            <div class="form-icon">
                                                 {{ form.name }}
                                                <span class="cus-icon"><i class="feather-user"></i></span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label class="col-form-label">{{ form.email.label }}</label>
                                            <div class="form-icon">
                                                {{ form.email }}
                                                <span class="cus-icon"><i class="feather-mail"></i></span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label class="col-form-label">{{ form.phone_number.label }}</label>
                                            <div class="form-icon">
                                               {{ form.phone_number }}
                                                <span class="cus-icon"><i class="feather-phone"></i></span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label class="col-form-label">{{ form.message.label }}</label>
                                            <div class="form-icon form-msg">
                                                {{ form.message }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-12 text-center">
                                        <button class="btn btn-primary" type="submit">Send Message<i
                                                class="feather-arrow-right-circle ms-2"></i></button>
                                    </div>
                                </div>
                            </form>
                        </div>

                    </div>
                </div>
            </div>
        </div>
{% endblock %}

user/templates/provider/provider-list.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}
	 <div class="breadcrumb-bar">
            <div class="container">
            	<br>
            	<br>
            	<br>
                <div class="row">
                    <div class="col-md-12">
                        <h2 class="breadcrumb-title mb-0">Providers</h2>
                    </div>
                </div>
            </div>
        </div>
        <div class="content">
            <div class="container">
                <div class="row">
                	 {% for provider_service in provider_services %}
	                    <div class="col-lg-3 col-sm-6">
	                    	{% if provider_service.provider.id %}
	                    	{% with provider_id=provider_service.provider.id %}
	                        <div class="providerset">
	                            
					                
					                    <div class="providerset-img">
					                        <a href="{% url 'user:provider_details' provider_id=provider_id %}">
					                            {% if provider_service.picture %}
					                                <img src="{{ provider_service.picture.url }}" alt="img">
					                            
					                            {% else %}
					                                <img src="{% static 'assets/img/provider/provider-11.jpg' %}" alt="img">
					                            {% endif %}
					                        </a>
					                    </div>
					                
	                            <div class="providerset-content">
	                                <div class="providerset-price">
	                                    <div class="providerset-name">
	                                        <h4><a href="{% url 'user:provider_details' provider_id=provider_id %}">{{provider_service.provider.first_name}}</a><i class="fa fa-check-circle"
	                                                aria-hidden="true"></i></h4>
	                                        <span>{{provider_service.category.name}}</span>
	                                    </div>
	                                    <div class="providerset-prices">
	                                        <h6>${{provider_service.price}}<span>/hr</span></h6>
	                                    </div>
	                                </div>
	                            </div>
	                        </div>
	                        {% endwith %}
					            {% endif %}
	                    </div>
	                 {% endfor %}
                </div>
            </div>
        </div>
{% endblock %}

user/templates/provider/provider-sidebar.html
{% load static %}
<div class="sidebar" id="sidebar">
    <div class="sidebar-inner slimscroll">
        <div id="sidebar-menu" class="sidebar-menu">
            <ul>
                <li {% if active_menu == 'services' %}class="active"{% endif %}>
                    <a href="http://127.0.0.1:8000/service/service-list"><i class="feather-briefcase"></i> <span>My Services</span></a>
                </li>
                <li {% if active_menu == 'bookings' %}class="active"{% endif %}>
                    <a href="http://127.0.0.1:8000/user/provider-booking"><i class="feather-calendar"></i> <span>Bookings</span></a>
                </li>
                <li {% if active_menu == 'logout' %}class="active"{% endif %}>
                    <a href="http://127.0.0.1:8000/?action=logout"><i class="feather-log-out"></i> <span>Logout</span></a>
                </li>
            </ul>
        </div>
    </div>
</div>